import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import pg from 'pg';
import crypto from 'crypto';
const {Pool}=pg; const app=express(); const PORT=process.env.PORT||3000; const API_BASE='https://data.addlivetag.com/product-data/product-data.php';
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
app.use(helmet({contentSecurityPolicy:false})); app.use(express.json({limit:'30kb'})); app.use(express.static('public')); app.use('/api/',rateLimit({windowMs:60000,limit:120,standardHeaders:true,legacyHeaders:false}));
const q=(t,p=[])=>pool.query(t,p); const money=n=>Math.round(Number(n||0)*100)/100; const hash=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
const safeSub=(v,f='')=>String(v||f).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').replace(/-/g,'_').replace(/[^a-zA-Z0-9_.]/g,'_').replace(/_+/g,'_').slice(0,60);
function isShopeeInput(v){v=String(v||'').trim();if(/^\d{6,20}$/.test(v))return true;try{const u=new URL(v);return /(^|\.)shopee\.vn$/i.test(u.hostname)||/(^|\.)s\.shopee\.vn$/i.test(u.hostname)||/(^|\.)vn\.shp\.ee$/i.test(u.hostname)}catch{return false}}
function memberId(){return 'HP'+crypto.randomBytes(5).toString('hex').toUpperCase().slice(0,8)}
async function init(){if(!pool){console.warn('DATABASE_URL missing');return}await q(`
CREATE TABLE IF NOT EXISTS members(id BIGSERIAL PRIMARY KEY,member_code VARCHAR(16) UNIQUE NOT NULL,token_hash CHAR(64) NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW(),last_seen_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS links(id BIGSERIAL PRIMARY KEY,member_id BIGINT REFERENCES members(id),item_id TEXT,shop_id TEXT,product_name TEXT,price NUMERIC(16,2) DEFAULT 0,commission_est NUMERIC(16,2) DEFAULT 0,cashback_est NUMERIC(16,2) DEFAULT 0,affiliate_link TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS orders(id BIGSERIAL PRIMARY KEY,member_id BIGINT REFERENCES members(id),external_order_id TEXT UNIQUE,platform VARCHAR(20) DEFAULT 'shopee',amount NUMERIC(16,2) DEFAULT 0,commission NUMERIC(16,2) DEFAULT 0,cashback NUMERIC(16,2) DEFAULT 0,status VARCHAR(30) DEFAULT 'PENDING',created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS withdrawals(id BIGSERIAL PRIMARY KEY,member_id BIGINT REFERENCES members(id),amount NUMERIC(16,2) NOT NULL,status VARCHAR(30) DEFAULT 'REQUESTED',note TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS wallet_transactions(id BIGSERIAL PRIMARY KEY,member_id BIGINT REFERENCES members(id),direction VARCHAR(8) NOT NULL CHECK(direction IN ('CREDIT','DEBIT')),type VARCHAR(40) NOT NULL,amount NUMERIC(16,2) NOT NULL CHECK(amount>=0),ref_type VARCHAR(30),ref_id BIGINT,note TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE UNIQUE INDEX IF NOT EXISTS wallet_unique_event ON wallet_transactions(type,ref_type,ref_id) WHERE ref_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS links_member_created_idx ON links(member_id,created_at DESC);
CREATE INDEX IF NOT EXISTS orders_member_idx ON orders(member_id);
CREATE INDEX IF NOT EXISTS wallet_member_idx ON wallet_transactions(member_id,created_at DESC);
`)}
async function auth(req,res,next){if(!pool)return res.status(503).json({error:'Database chưa được cấu hình.'});const code=safeSub(req.get('x-member-id'),'').toUpperCase(),token=req.get('x-member-token')||'';if(!code||!token)return res.status(401).json({error:'Thiếu thông tin thành viên.'});const r=await q('SELECT * FROM members WHERE member_code=$1 AND token_hash=$2',[code,hash(token)]);if(!r.rows[0])return res.status(401).json({error:'Phiên thành viên không hợp lệ.'});req.member=r.rows[0];next()}
function admin(req,res,next){if(!process.env.ADMIN_KEY||req.get('x-admin-key')!==process.env.ADMIN_KEY)return res.status(401).json({error:'Không có quyền.'});next()}
async function walletBalance(memberId){const r=await q(`SELECT COALESCE(SUM(CASE WHEN direction='CREDIT' THEN amount ELSE -amount END),0) balance FROM wallet_transactions WHERE member_id=$1`,[memberId]);return Number(r.rows[0].balance||0)}
async function syncOrderLedger(order,previousStatus){if(!order)return;const nowAvailable=['AVAILABLE','PAID'].includes(order.status),wasAvailable=['AVAILABLE','PAID'].includes(previousStatus||'');if(nowAvailable&&!wasAvailable){await q(`INSERT INTO wallet_transactions(member_id,direction,type,amount,ref_type,ref_id,note) VALUES($1,'CREDIT','CASHBACK',$2,'ORDER',$3,$4) ON CONFLICT DO NOTHING`,[order.member_id,money(order.cashback),order.id,'Cashback '+order.external_order_id])}else if(!nowAvailable&&wasAvailable){const c=await q(`SELECT 1 FROM wallet_transactions WHERE type='CASHBACK' AND ref_type='ORDER' AND ref_id=$1`,[order.id]);if(c.rows[0])await q(`INSERT INTO wallet_transactions(member_id,direction,type,amount,ref_type,ref_id,note) VALUES($1,'DEBIT','CASHBACK_REVERSAL',$2,'ORDER_REVERSAL',$3,$4) ON CONFLICT DO NOTHING`,[order.member_id,money(order.cashback),order.id,'Hoàn tác cashback '+order.external_order_id])}}
app.post('/api/member/init',async(req,res)=>{try{if(!pool)return res.status(503).json({error:'Database chưa được cấu hình.'});const oldCode=safeSub(req.body?.member,'').toUpperCase(),oldToken=String(req.body?.token||'');if(oldCode&&oldToken){const r=await q('UPDATE members SET last_seen_at=NOW() WHERE member_code=$1 AND token_hash=$2 RETURNING member_code',[oldCode,hash(oldToken)]);if(r.rows[0])return res.json({member:r.rows[0].member_code,token:oldToken,recovered:true})}let code,token=crypto.randomBytes(24).toString('base64url');for(let i=0;i<8;i++){code=memberId();try{await q('INSERT INTO members(member_code,token_hash) VALUES($1,$2)',[code,hash(token)]);break}catch(e){if(e.code!=='23505')throw e}}res.json({member:code,token,recovered:false})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/dashboard',auth,async(req,res)=>{try{const m=req.member.id;const [pending,withdrawals,links,count,paid]=await Promise.all([q(`SELECT COALESCE(SUM(cashback),0) n FROM orders WHERE member_id=$1 AND status IN ('PENDING','APPROVED')`,[m]),q(`SELECT COALESCE(SUM(amount) FILTER (WHERE status IN ('REQUESTED','PROCESSING')),0) reserved FROM withdrawals WHERE member_id=$1`,[m]),q('SELECT id,item_id,product_name,price,commission_est,cashback_est,created_at FROM links WHERE member_id=$1 ORDER BY id DESC LIMIT 10',[m]),q(`SELECT COUNT(*) n FROM links WHERE member_id=$1 AND created_at >= CURRENT_DATE`,[m]),q(`SELECT COALESCE(SUM(amount),0) n FROM withdrawals WHERE member_id=$1 AND status='PAID'`,[m])]);const ledger=await walletBalance(m),reserved=Number(withdrawals.rows[0].reserved||0);res.json({member:req.member.member_code,balance:{available:money(Math.max(0,ledger-reserved)),pending:money(pending.rows[0].n),paid:money(paid.rows[0].n),withdrawRequested:money(reserved)},todayLinks:+count.rows[0].n,links:links.rows})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/convert',auth,async(req,res)=>{try{const input=String(req.body?.url||'').trim();if(!isShopeeInput(input))return res.status(400).json({error:'Vui lòng nhập link Shopee Việt Nam hoặc Item ID hợp lệ.'});const apiKey=process.env.ADDLIVETAG_API_KEY,affiliateId=process.env.SHOPEE_AFFILIATE_ID;if(!apiKey||!affiliateId)return res.status(503).json({error:'Server chưa cấu hình API/Affiliate ID.'});const params=new URLSearchParams();/^\d{6,20}$/.test(input)?params.set('item_id',input):params.set('url',input);params.set('affid',affiliateId);params.set('sub1',req.member.member_code);params.set('sub2','C01');params.set('sub3','web');params.set('sub4','');params.set('sub5','');const upstream=await fetch(`${API_BASE}?${params}`,{headers:{'X-API-Key':apiKey,Accept:'application/json'},signal:AbortSignal.timeout(15000)});const raw=await upstream.text();let data;try{data=JSON.parse(raw)}catch{throw new Error('API trả dữ liệu không hợp lệ.')}if(!upstream.ok||data?.status!=='success'||!data?.productInfo)return res.status(502).json({error:data?.message||data?.error||'Không lấy được thông tin sản phẩm.'});const p=data.productInfo,price=Number(p.price||0),commission=Number(p.commission||0),cashback=commission*.8,aff=p.affLink||null;const lr=await q('INSERT INTO links(member_id,item_id,shop_id,product_name,price,commission_est,cashback_est,affiliate_link) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[req.member.id,String(p.itemId||''),String(p.shopId||''),p.productName||p.name||'Sản phẩm Shopee',price,commission,cashback,aff]);res.json({linkId:lr.rows[0].id,itemId:String(p.itemId||''),shopId:String(p.shopId||''),name:p.productName||p.name||'Sản phẩm Shopee',image:p.imageUrl||p.image||p.imageUrlList?.[0]||null,price,sales:Number(p.sales||0),rating:Number(p.rating||0),commission,commissionRate:price>0?commission/price:null,affiliateLink:aff,member:req.member.member_code,cashbackRate:.8,estimatedCashback:cashback,estimated:true})}catch(e){res.status(e?.name==='TimeoutError'?504:500).json({error:e?.name==='TimeoutError'?'API phản hồi quá chậm, vui lòng thử lại.':e.message})}});
app.post('/api/withdrawals',auth,async(req,res)=>{try{const amount=money(req.body?.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Số tiền không hợp lệ.'});const ledger=await walletBalance(req.member.id);const p=await q(`SELECT COALESCE(SUM(amount),0) n FROM withdrawals WHERE member_id=$1 AND status IN ('REQUESTED','PROCESSING')`,[req.member.id]);const available=ledger-Number(p.rows[0].n);if(amount>available)return res.status(400).json({error:'Số dư khả dụng không đủ.'});const r=await q('INSERT INTO withdrawals(member_id,amount) VALUES($1,$2) RETURNING id,status,amount,created_at',[req.member.id,amount]);res.json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/summary',admin,async(req,res)=>{try{const [m,l,o,w,ledger]=await Promise.all([q('SELECT COUNT(*) n FROM members'),q('SELECT COUNT(*) n FROM links'),q('SELECT COUNT(*) n,COALESCE(SUM(commission),0) commission,COALESCE(SUM(cashback),0) cashback FROM orders'),q("SELECT COUNT(*) n,COALESCE(SUM(amount),0) amount FROM withdrawals WHERE status IN ('REQUESTED','PROCESSING')"),q(`SELECT COALESCE(SUM(CASE WHEN direction='CREDIT' THEN amount ELSE -amount END),0) n FROM wallet_transactions`)]);res.json({members:+m.rows[0].n,links:+l.rows[0].n,orders:+o.rows[0].n,commission:+o.rows[0].commission,cashback:+o.rows[0].cashback,wallet:+ledger.rows[0].n,withdrawals:+w.rows[0].n,withdrawalAmount:+w.rows[0].amount})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/orders',admin,async(req,res)=>{try{const r=await q(`SELECT o.*,m.member_code FROM orders o JOIN members m ON m.id=o.member_id ORDER BY o.id DESC LIMIT 300`);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/orders',admin,async(req,res)=>{try{const {member,orderId,amount=0,commission=0,status='PENDING'}=req.body||{};const mr=await q('SELECT id FROM members WHERE member_code=$1',[safeSub(member,'').toUpperCase()]);if(!mr.rows[0])return res.status(404).json({error:'Không tìm thấy thành viên.'});const allowed=['PENDING','APPROVED','AVAILABLE','PAID','REJECTED'];if(!allowed.includes(status))return res.status(400).json({error:'Trạng thái không hợp lệ.'});const old=await q('SELECT * FROM orders WHERE external_order_id=$1',[String(orderId)]);const cashback=money(Number(commission)*.8);const r=await q(`INSERT INTO orders(member_id,external_order_id,amount,commission,cashback,status) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(external_order_id) DO UPDATE SET member_id=EXCLUDED.member_id,amount=EXCLUDED.amount,commission=EXCLUDED.commission,cashback=EXCLUDED.cashback,status=EXCLUDED.status,updated_at=NOW() RETURNING *`,[mr.rows[0].id,String(orderId),money(amount),money(commission),cashback,status]);await syncOrderLedger(r.rows[0],old.rows[0]?.status);res.json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.patch('/api/admin/orders/:id',admin,async(req,res)=>{try{const allowed=['PENDING','APPROVED','AVAILABLE','PAID','REJECTED'];const status=String(req.body?.status||'');if(!allowed.includes(status))return res.status(400).json({error:'Trạng thái không hợp lệ.'});const old=await q('SELECT * FROM orders WHERE id=$1',[req.params.id]);if(!old.rows[0])return res.status(404).json({error:'Không tìm thấy đơn.'});const r=await q('UPDATE orders SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[status,req.params.id]);await syncOrderLedger(r.rows[0],old.rows[0].status);res.json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/members',admin,async(req,res)=>{try{const s=String(req.query.search||'').trim().toUpperCase(),p=[];let where='';if(s){p.push('%'+s+'%');where='WHERE m.member_code LIKE $1'}const r=await q(`SELECT m.id,m.member_code,m.created_at,m.last_seen_at,COUNT(DISTINCT l.id)::int links_count,COUNT(DISTINCT o.id)::int orders_count FROM members m LEFT JOIN links l ON l.member_id=m.id LEFT JOIN orders o ON o.member_id=m.id ${where} GROUP BY m.id ORDER BY m.id DESC LIMIT 300`,p);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/members/:code',admin,async(req,res)=>{try{const code=safeSub(req.params.code,'').toUpperCase();const mr=await q('SELECT id,member_code,created_at,last_seen_at FROM members WHERE member_code=$1',[code]);if(!mr.rows[0])return res.status(404).json({error:'Không tìm thấy thành viên.'});const id=mr.rows[0].id;const [links,orders,wallet,withdrawals]=await Promise.all([q('SELECT id,product_name,price,commission_est,cashback_est,created_at FROM links WHERE member_id=$1 ORDER BY id DESC LIMIT 50',[id]),q('SELECT id,external_order_id,amount,commission,cashback,status,created_at,updated_at FROM orders WHERE member_id=$1 ORDER BY id DESC LIMIT 50',[id]),q('SELECT id,direction,type,amount,ref_type,ref_id,note,created_at FROM wallet_transactions WHERE member_id=$1 ORDER BY id DESC LIMIT 100',[id]),q('SELECT id,amount,status,note,created_at FROM withdrawals WHERE member_id=$1 ORDER BY id DESC LIMIT 50',[id])]);const ledger=await walletBalance(id);res.json({member:mr.rows[0],ledgerBalance:ledger,links:links.rows,orders:orders.rows,wallet:wallet.rows,withdrawals:withdrawals.rows})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/withdrawals',admin,async(req,res)=>{try{const r=await q(`SELECT w.id,w.amount,w.status,w.note,w.created_at,w.updated_at,m.member_code FROM withdrawals w JOIN members m ON m.id=w.member_id ORDER BY w.id DESC LIMIT 300`);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.patch('/api/admin/withdrawals/:id',admin,async(req,res)=>{try{const allowed=['REQUESTED','PROCESSING','PAID','REJECTED'];const status=String(req.body?.status||'');if(!allowed.includes(status))return res.status(400).json({error:'Trạng thái không hợp lệ.'});const old=await q('SELECT * FROM withdrawals WHERE id=$1',[req.params.id]);if(!old.rows[0])return res.status(404).json({error:'Không tìm thấy yêu cầu.'});const r=await q('UPDATE withdrawals SET status=$1,note=COALESCE($2,note),updated_at=NOW() WHERE id=$3 RETURNING *',[status,req.body?.note??null,req.params.id]);if(status==='PAID'&&old.rows[0].status!=='PAID')await q(`INSERT INTO wallet_transactions(member_id,direction,type,amount,ref_type,ref_id,note) VALUES($1,'DEBIT','WITHDRAWAL',$2,'WITHDRAWAL',$3,$4) ON CONFLICT DO NOTHING`,[r.rows[0].member_id,money(r.rows[0].amount),r.rows[0].id,'Rút tiền #'+r.rows[0].id]);res.json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/links',admin,async(req,res)=>{try{const r=await q(`SELECT l.id,l.product_name,l.item_id,l.price,l.commission_est,l.cashback_est,l.created_at,m.member_code FROM links l JOIN members m ON m.id=l.member_id ORDER BY l.id DESC LIMIT 300`);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/health',async(_req,res)=>{if(!pool)return res.json({ok:true,database:false});try{await q('SELECT 1');res.json({ok:true,database:true,version:'4.2'})}catch{res.status(503).json({ok:false,database:false})}});
init().then(()=>app.listen(PORT,()=>console.log(`HoanLink V4.2 running on port ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
